import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import {
  Box, Button, Card, CardContent, CardMedia, Divider,
  Drawer, Grid,
  List,
  ListItem,
  ListItemText, Slide,Grow,
  Typography,
} from '@mui/material';
import Link from 'next/link';
import defaultUrl from '@/constant/url';

const inter = Inter({ subsets: ['latin'] });

export default function Home ({data}) {
  const { notices = [], rules = [], courses= [] } = data;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>
        <Typography sx={{
          fontFamily: 'var(--myfont-font)',
          fontSize: 20
        }}>
          实验室安全准入教育
        </Typography>
        <Typography gutterBottom sx={{
          mb:2
        }}>
          实验室是科研机构相关人员从事科研工作的主要场所,也是重大科研成果的诞生地。实验室安全是推进科研活动不断正常向前开展的基本保证。实验室安全准入教育是加强实验室规范教育的系统工程，面向教师、学生进行实验安全、操作规范和专业能力教育与考核，考核合格、具备相应实验知识、能力、素质的人员获得准入资格才可以进入实验室管理、教学与学习、研究。围绕“安全意识树立、安全知识掌握、安全技能运用”的教育目标，建立科学完善的实验室安全课程及考核体系，使实验室达到一种安全、稳定、和谐的可持续状态。
        </Typography>

        <Grid container spacing={0}>
          <Grid xs={12} sm={6} item>
            <Box>
              <Box display={'flex'} sx={{
                mb: -1
              }}>
                <Typography sx={{
                  fontFamily: 'var(--myfont-font)',
                  fontSize: 18,
                  lineHeight: 2
                }}>
                  最新通知公告
                </Typography>
                <Button ><Link
                  href={'/notices'}>更多</Link></Button>
              </Box>
              <List component="nav" aria-label="mailbox folders"
                    sx={{ paddingRight: 5 }}>
                {notices.map((value, index) => (
                  <ListItem divider button key={index}>
                    <Link style={{
                      width: '100%'
                    }} href={'/notices/' + value.id}>
                      <Typography noWrap={true} sx={{
                        overflow: 'hidden',
                        whiteSpace: 'nowrap',
                        textOrientation: 'ellipsis'
                      }}>{value.title}</Typography>
                    </Link>
                  </ListItem>
                ))}
              </List>
            </Box>
          </Grid>
          <Grid xs={12} sm={6} item>
            <Box>
              <Box display={'flex'} sx={{
                mb: -1
              }}>
                <Typography sx={{
                  fontFamily: 'var(--myfont-font)',
                  fontSize: 18,
                  lineHeight: 2
                }}>
                  最新规章制度
                </Typography>
                <Button ><Link
                  href={'/rules'}>更多</Link></Button>
              </Box>
              <List component="nav" aria-label="mailbox folders"
                    sx={{ paddingRight: 5 }}>
                {rules.map((value, index) => (
                  <ListItem divider button key={index}>
                    <Link style={{
                      width: '100%'
                    }} href={'/rules/' + value.id}>
                      <Typography noWrap={true}>{value.title}</Typography>
                    </Link>
                  </ListItem>
                ))}
              </List>
            </Box>
          </Grid>
        </Grid>
        <Grid container>
          <Box display={'flex'} sx={{
            mt: 1,
            mb: 1
          }}>
            <Typography sx={{
              fontFamily: 'var(--myfont-font)',
              fontSize: 18,
              lineHeight: 2
            }}>
              最新课程
            </Typography>
            <Button ><Link
              href={'/learn'}>更多</Link></Button>
          </Box>
          <Grid container sx={{ height: 240 }} spacing={2}>

            {courses.map((val, index) => (
              <Grow in timeout={300+index*50} key={index}>
                <Grid xs={3} item key={index}>
                  <Card>
                    <Link href={'/learn/'+val.id}>
                    <CardMedia
                      component="img"
                      image={defaultUrl+'/'+val.imgName}
                      alt="Paella dish"
                    />
                    </Link>
                    {/*<CardContent>*/}
                    {/*</CardContent>*/}
                  </Card>
                  <Typography gutterBottom component="div" sx={{
                    fontFamily: 'var(--myfont-font)',
                  }}>
                    {val.name}
                  </Typography>
                </Grid>
              </Grow>
            ))}
          </Grid>
        </Grid>
      </main>
    </>
  );
}

export async function getServerSideProps(content) {
  // Fetch data from external API
  const res = await fetch(defaultUrl+`/index`)
  const data = await res.json()
  // Pass data to the page via props
  return { props: { data } }
}
